[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://mias-brooklyn-bakery.onrender.com/api"
  NEXT_PUBLIC_WS_URL = "wss://mias-brooklyn-bakery.onrender.com"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://mias-brooklyn-bakery.onrender.com/api/:splat"
  status = 200
  force = true

[context.production.environment]
  NEXT_PUBLIC_ENV = "production"
  NEXT_PUBLIC_DEMO_MODE = "true"

[context.deploy-preview.environment]
  NEXT_PUBLIC_ENV = "preview"

[context.branch-deploy.environment]
  NEXT_PUBLIC_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"