#!/bin/bash

echo "🍞 Starting Mia's Brooklyn Bakery Backend Server..."
echo ""
echo "Demo Mode: Enabled"
echo "Port: 3002"
echo "Frontend URL: http://localhost:3000"
echo ""
echo "📋 Demo Login Credentials:"
echo "  Owner: sarah@miasbakery.com / password123"
echo "  Manager (Brooklyn): mike.brooklyn@miasbakery.com / password123"
echo "  Manager (UES): emma.ues@miasbakery.com / password123"
echo "  Driver: carlos@miasbakery.com / password123"
echo "  Kitchen: julia.kitchen@miasbakery.com / password123"
echo ""
echo "🌐 Available Endpoints:"
echo "  Health Check: http://localhost:3002/health"
echo "  API Documentation: http://localhost:3002/api"
echo "  Demo Credentials: http://localhost:3002/api/auth/demo-credentials"
echo ""
echo "⚡ Real-time Features:"
echo "  - WebSocket server for live updates"
echo "  - Automatic order generation every 30 seconds"
echo "  - Driver location simulation"
echo "  - Kitchen status updates"
echo "  - Live analytics broadcasts"
echo ""
echo "🚀 Starting server..."
echo "   Press Ctrl+C to stop"
echo ""

DEMO_MODE=true PORT=3002 node dist/server.js